version: "3.0"
services:
  elasticsearch:
    image: elasticsearch:7.6.0
    ports: 
      - 9200:9200
    volumes:      
      - ./data:/usr/share/elasticsearch/data
    environment: 
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 5601:5601