FROM mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04

ENV SA_PASSWORD="Passw0rd"
 
ENV ACCEPT_EULA=Y

WORKDIR /usr/src/sql

COPY ./gendb.sql .
COPY ./entrypoint.sh .
COPY ./create-db.sh .

CMD /bin/bash ./entrypoint.sh


# RUN (/opt/mssql/bin/sqlservr --accept-eula & sleep 10) \
# CMD /opt/mssql-tools/bin/sqlcmd -i gendb.sql -S localhost -U sa -P "Passw0rd" \
# && .\start -sa_password $env:sa_password -ACCEPT_EULA $env:ACCEPT_EULA -attach_dbs \"$env:attach_dbs\" -Verbose
