server:
  app:
    port: 4000
  corsOptions:
    origin:
      http://localhost:4200
  dbConfig:
      user: ofer
      password: password1234
      database: FakeLook
      server: localhost
  log:
    maxSize: 32768
    paths:
      log: ./logs/log.log
      access: logs/access.log
      error: logs/error.log
  imagesPath: \images\
